Upgrade bashly to 1.3.5 and refactor HTTP parsing functions

diff --git a/keencli b/keencli
--- a/keencli
+++ b/keencli
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.12 (https://bashly.dev)
+# This script was generated by bashly 1.3.5 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n" >&2
+if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
+  printf "bash version 4.2 or higher is required\n" >&2
   exit 1
 fi
 
@@ -35,6 +35,7 @@ keencli_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -77,6 +78,7 @@ keencli_request_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -145,6 +147,7 @@ keencli_show_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -166,6 +169,7 @@ keencli_show_system_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -215,6 +219,7 @@ keencli_show_interface_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -279,6 +284,7 @@ keencli_show_ip_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -305,6 +311,7 @@ keencli_show_ip_hotspot_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -326,6 +333,7 @@ keencli_show_ip_hotspot_list_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -377,6 +385,7 @@ keencli_show_ip_hotspot_summary_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -443,6 +452,7 @@ keencli_show_internet_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -492,6 +502,7 @@ keencli_show_ntce_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -513,6 +524,7 @@ keencli_show_ntce_summary_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -586,6 +598,7 @@ keencli_config_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -634,6 +647,7 @@ keencli_log_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -673,6 +687,7 @@ keencli_self_test_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -735,6 +750,8 @@ normalize_input() {
 
 # :command.inspect_args
 inspect_args() {
+  local k
+
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
@@ -766,7 +783,6 @@ inspect_args() {
 
 # :command.user_lib
 # src/lib/colors.sh
-
 enable_auto_colors() {
   if [[ -z ${NO_COLOR+x} && ! -t 1 ]]; then
     NO_COLOR=1
@@ -901,7 +917,10 @@ function debug() {
 # src/lib/functions/md5_hash.sh
 # shellcheck disable=SC2154
 function md5_hash() {
-  echo -n "$1" | "${deps[md5]}" | awk '{print $1}'
+  local hash_output
+
+  hash_output=$(echo -n "$1" | "${deps[md5]}")
+  echo "${hash_output%% *}"
 }
 
 # src/lib/http/get_http_cookie_path.sh
@@ -915,27 +934,35 @@ function get_http_cookie_path() {
 
 # src/lib/http/get_http_header_value.sh
 function get_http_header_value() {
-  local key response
+  local key response line header_value
 
   key="${1:?header key must be set}"
   response="${2:?response must be set}"
 
-  echo "${response}" |
-    grep "${key}" |
-    awk -F ": " '{print $2}' |
-    tr -d '\r'
+  while IFS= read -r line; do
+    line="${line%$'\r'}"
+    if [[ "${line,,}" == "${key,,}:"* ]]; then
+      header_value="${line#*: }"
+      echo "${header_value}"
+      return 0
+    fi
+  done <<<"${response}"
 }
 
 # src/lib/http/get_http_status_code.sh
 function get_http_status_code() {
-  local response
+  local response first_line
+
   response="${1:?response must be set}"
 
-  echo "${response}" |
-    tail -n +1 |
-    head -1 |
-    grep -e "^HTTP" |
-    awk -F " " '{print $2}'
+  IFS=$'\n' read -ra lines <<<"${response}"
+  first_line="${lines[0]}"
+
+  if [[ "${first_line}" =~ ^HTTP[[:space:]]+([0-9]+) ]]; then
+    echo "${BASH_REMATCH[1]}"
+  elif [[ "${first_line}" =~ ^HTTP/[0-9.]+[[:space:]]+([0-9]+) ]]; then
+    echo "${BASH_REMATCH[1]}"
+  fi
 }
 
 # src/lib/http/http_command.sh
@@ -1282,6 +1309,8 @@ keencli_self_test_command() {
 
 # :command.parse_requirements
 parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1421,6 +1450,8 @@ parse_requirements() {
 
 # :command.parse_requirements
 keencli_request_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1525,9 +1556,12 @@ keencli_request_parse_requirements() {
 
   # :command.validations
   # :argument.validations
-  if [[ -v args['request_data'] && -n $(validate_json "${args['request_data']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "REQUEST_DATA" "$(validate_json "${args['request_data']:-}")" >&2
-    exit 1
+  if [[ -v args['request_data'] ]]; then
+    validation_output="$(validate_json "${args['request_data']:-}")"
+    if [[ -n "$validation_output" ]]; then
+      printf "validation error in %s:\n%s\n" "REQUEST_DATA" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
@@ -1558,6 +1592,8 @@ keencli_request_parse_requirements() {
 
 # :command.parse_requirements
 keencli_show_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1654,6 +1690,8 @@ keencli_show_parse_requirements() {
 
 # :command.parse_requirements
 keencli_show_system_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1779,6 +1817,8 @@ keencli_show_system_parse_requirements() {
 
 # :command.parse_requirements
 keencli_show_interface_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1908,6 +1948,8 @@ keencli_show_interface_parse_requirements() {
 
 # :command.parse_requirements
 keencli_show_ip_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1976,6 +2018,8 @@ keencli_show_ip_parse_requirements() {
 
 # :command.parse_requirements
 keencli_show_ip_hotspot_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -2051,6 +2095,8 @@ keencli_show_ip_hotspot_parse_requirements() {
 
 # :command.parse_requirements
 keencli_show_ip_hotspot_list_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -2180,6 +2226,8 @@ keencli_show_ip_hotspot_list_parse_requirements() {
 
 # :command.parse_requirements
 keencli_show_ip_hotspot_summary_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -2348,6 +2396,8 @@ keencli_show_ip_hotspot_summary_parse_requirements() {
 
 # :command.parse_requirements
 keencli_show_internet_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -2463,6 +2513,8 @@ keencli_show_internet_parse_requirements() {
 
 # :command.parse_requirements
 keencli_show_ntce_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -2531,6 +2583,8 @@ keencli_show_ntce_parse_requirements() {
 
 # :command.parse_requirements
 keencli_show_ntce_summary_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -2718,6 +2772,8 @@ keencli_show_ntce_summary_parse_requirements() {
 
 # :command.parse_requirements
 keencli_config_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -2831,6 +2887,8 @@ keencli_config_parse_requirements() {
 
 # :command.parse_requirements
 keencli_log_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -2925,6 +2983,8 @@ keencli_log_parse_requirements() {
 
 # :command.parse_requirements
 keencli_self_test_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -3055,6 +3115,8 @@ run() {
 }
 
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  # :command.start
+  command_line_args=("$@")
   initialize
-  run "$@"
+  run "${command_line_args[@]}"
 fi
