Bump version and main script

diff --git a/keencli b/keencli
--- a/keencli
+++ b/keencli
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.2.12 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -745,15 +745,6 @@ inspect_args() {
     echo args: none
   fi
 
-  if ((${#other_args[@]})); then
-    echo
-    echo other_args:
-    echo "- \${other_args[*]} = ${other_args[*]}"
-    for i in "${!other_args[@]}"; do
-      echo "- \${other_args[$i]} = ${other_args[$i]}"
-    done
-  fi
-
   if ((${#deps[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
@@ -775,10 +766,17 @@ inspect_args() {
 
 # :command.user_lib
 # src/lib/colors.sh
+
+enable_auto_colors() {
+  if [[ -z ${NO_COLOR+x} && ! -t 1 ]]; then
+    NO_COLOR=1
+  fi
+}
+
 print_in_color() {
   local color="$1"
   shift
-  if [[ -z ${NO_COLOR+x} ]]; then
+  if [[ "${NO_COLOR:-}" == "" ]]; then
     printf "$color%b\e[0m\n" "$*"
   else
     printf "%b\n" "$*"
@@ -1313,26 +1311,34 @@ parse_requirements() {
   env_var_names+=("KEENETIC_PASSWORD")
 
   # :command.dependencies_filter
-  if command -v curl >/dev/null 2>&1; then
-    deps['curl']="$(command -v curl | head -n1)"
-  else
+  missing_deps=
+  # :dependency.filter
+  if ! command -v curl >/dev/null 2>&1; then
     printf "missing dependency: curl\n" >&2
-    printf "%s\n" "https://curl.se/" >&2
-    exit 1
+    printf "%s\n\n" "https://curl.se/" >&2
+    missing_deps=1
+  else
+    deps['curl']="$(command -v curl | head -n1)"
   fi
 
-  if command -v yq >/dev/null 2>&1; then
-    deps['yq']="$(command -v yq | head -n1)"
-  else
+  # :dependency.filter
+  if ! command -v yq >/dev/null 2>&1; then
     printf "missing dependency: yq\n" >&2
-    printf "%s\n" "https://mikefarah.gitbook.io/yq/" >&2
-    exit 1
+    printf "%s\n\n" "https://mikefarah.gitbook.io/yq/" >&2
+    missing_deps=1
+  else
+    deps['yq']="$(command -v yq | head -n1)"
   fi
 
-  if command -v md5sum md5 >/dev/null 2>&1; then
-    deps['md5']="$(command -v md5sum md5 | head -n1)"
-  else
+  # :dependency.filter
+  if ! command -v md5sum md5 >/dev/null 2>&1; then
     printf "missing dependency: md5 (md5sum/md5)\n" >&2
+    missing_deps=1
+  else
+    deps['md5']="$(command -v md5sum md5 | head -n1)"
+  fi
+
+  if [[ -n $missing_deps ]]; then
     exit 1
   fi
 
@@ -1506,6 +1512,7 @@ keencli_request_parse_requirements() {
 
     esac
   done
+
   # :command.required_args_filter
   if [[ -z ${args['url_path']+x} ]]; then
     printf "missing required argument: URL_PATH\nusage: keencli request URL_PATH [REQUEST_DATA] [OPTIONS]\n" >&2
@@ -1524,15 +1531,21 @@ keencli_request_parse_requirements() {
   fi
 
   # :flag.validations
-  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
-    exit 1
+  if [[ -v args['--baseurl'] ]]; then
+    validation_output="$(validate_base_url "${args['--baseurl']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
-  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
-    exit 1
+  if [[ -v args['--output'] ]]; then
+    validation_output="$(validate_file_path "${args['--output']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :command.whitelist_filter
@@ -1735,15 +1748,21 @@ keencli_show_system_parse_requirements() {
 
   # :command.validations
   # :flag.validations
-  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
-    exit 1
+  if [[ -v args['--baseurl'] ]]; then
+    validation_output="$(validate_base_url "${args['--baseurl']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
-  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
-    exit 1
+  if [[ -v args['--output'] ]]; then
+    validation_output="$(validate_file_path "${args['--output']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :command.whitelist_filter
@@ -1858,15 +1877,21 @@ keencli_show_interface_parse_requirements() {
 
   # :command.validations
   # :flag.validations
-  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
-    exit 1
+  if [[ -v args['--baseurl'] ]]; then
+    validation_output="$(validate_base_url "${args['--baseurl']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
-  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
-    exit 1
+  if [[ -v args['--output'] ]]; then
+    validation_output="$(validate_file_path "${args['--output']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :command.whitelist_filter
@@ -2128,15 +2153,21 @@ keencli_show_ip_hotspot_list_parse_requirements() {
 
   # :command.validations
   # :flag.validations
-  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
-    exit 1
+  if [[ -v args['--baseurl'] ]]; then
+    validation_output="$(validate_base_url "${args['--baseurl']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
-  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
-    exit 1
+  if [[ -v args['--output'] ]]; then
+    validation_output="$(validate_file_path "${args['--output']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :command.whitelist_filter
@@ -2282,15 +2313,21 @@ keencli_show_ip_hotspot_summary_parse_requirements() {
 
   # :command.validations
   # :flag.validations
-  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
-    exit 1
+  if [[ -v args['--baseurl'] ]]; then
+    validation_output="$(validate_base_url "${args['--baseurl']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
-  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
-    exit 1
+  if [[ -v args['--output'] ]]; then
+    validation_output="$(validate_file_path "${args['--output']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :command.whitelist_filter
@@ -2399,15 +2436,21 @@ keencli_show_internet_parse_requirements() {
 
   # :command.validations
   # :flag.validations
-  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
-    exit 1
+  if [[ -v args['--baseurl'] ]]; then
+    validation_output="$(validate_base_url "${args['--baseurl']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
-  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
-    exit 1
+  if [[ -v args['--output'] ]]; then
+    validation_output="$(validate_file_path "${args['--output']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :command.whitelist_filter
@@ -2636,15 +2679,21 @@ keencli_show_ntce_summary_parse_requirements() {
 
   # :command.validations
   # :flag.validations
-  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
-    exit 1
+  if [[ -v args['--baseurl'] ]]; then
+    validation_output="$(validate_base_url "${args['--baseurl']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
-  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
-    exit 1
+  if [[ -v args['--output'] ]]; then
+    validation_output="$(validate_file_path "${args['--output']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :command.whitelist_filter
@@ -2742,6 +2791,7 @@ keencli_config_parse_requirements() {
 
     esac
   done
+
   # :command.required_args_filter
   if [[ -z ${args['configuration_file']+x} ]]; then
     printf "missing required argument: CONFIGURATION_FILE\nusage: keencli config CONFIGURATION_FILE [OPTIONS]\n" >&2
@@ -2754,15 +2804,21 @@ keencli_config_parse_requirements() {
 
   # :command.validations
   # :flag.validations
-  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
-    exit 1
+  if [[ -v args['--baseurl'] ]]; then
+    validation_output="$(validate_base_url "${args['--baseurl']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
-  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
-    exit 1
+  if [[ -v args['--output'] ]]; then
+    validation_output="$(validate_file_path "${args['--output']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :command.whitelist_filter
@@ -2848,15 +2904,21 @@ keencli_log_parse_requirements() {
 
   # :command.validations
   # :flag.validations
-  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
-    exit 1
+  if [[ -v args['--baseurl'] ]]; then
+    validation_output="$(validate_base_url "${args['--baseurl']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
-  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
-    exit 1
+  if [[ -v args['--output'] ]]; then
+    validation_output="$(validate_file_path "${args['--output']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
 }
@@ -2936,34 +2998,41 @@ keencli_self_test_parse_requirements() {
 
   # :command.validations
   # :flag.validations
-  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
-    exit 1
+  if [[ -v args['--baseurl'] ]]; then
+    validation_output="$(validate_base_url "${args['--baseurl']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
   # :flag.validations
-  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
-    exit 1
+  if [[ -v args['--output'] ]]; then
+    validation_output="$(validate_file_path "${args['--output']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
 }
 
 # :command.initialize
 initialize() {
-  version="0.4.0"
-  long_usage=''
+  declare -g version="0.4.4"
   set -e
 
 }
 
 # :command.run
 run() {
+  # :command.globals
+  declare -g long_usage=''
   declare -g -A args=()
   declare -g -A deps=()
-  declare -g -a other_args=()
   declare -g -a env_var_names=()
   declare -g -a input=()
+
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
@@ -2985,5 +3054,7 @@ run() {
   esac
 }
 
-initialize
-run "$@"
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  initialize
+  run "$@"
+fi
