Add bash completions

diff --git a/keencli b/keencli
--- a/keencli
+++ b/keencli
@@ -34,8 +34,9 @@ keencli_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Log in to a Keenetic router\n" "login  "
-  printf "  %s   Make a http-request to a Keenetic router\n" "request"
+  printf "  %s   Log in to a Keenetic router\n" "login      "
+  printf "  %s   Make a http-request to a Keenetic router\n" "request    "
+  printf "  %s   Generate bash completions\n" "completions"
   echo
 
   # :command.long_usage
@@ -133,8 +134,53 @@ keencli_request_usage() {
   fi
 
   printf "%s\n" "Usage:"
-  printf "  keencli request URL_PATH [REQUEST_DATA] [OPTIONS]\n"
-  printf "  keencli request --help\n"
+  printf "  keencli request URL_PATH [REQUEST_DATA]\n"
+  printf "  keencli request --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "URL_PATH"
+    printf "    URL path (example \`/rci/show/system/\`)\n"
+    echo
+
+    # :argument.usage
+    printf "  %s\n" "REQUEST_DATA"
+    printf "    Request data (if the request_data parameter is specified, a POST request\n    will be made)\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+keencli_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "keencli completions\n"
+    echo
+
+    printf "  Generate bash completions\n  Usage: eval \"\$(keencli completions)\"\n"
+    echo
+
+  else
+    printf "keencli completions - Generate bash completions\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  keencli completions [OPTIONS]\n"
+  printf "  keencli completions --help\n"
   echo
 
   # :command.long_usage
@@ -179,19 +225,6 @@ keencli_request_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help"
     printf "    Show this help\n"
-    echo
-
-    # :command.usage_args
-    printf "%s\n" "Arguments:"
-
-    # :argument.usage
-    printf "  %s\n" "URL_PATH"
-    printf "    URL path (example \`/rci/show/system/\`)\n"
-    echo
-
-    # :argument.usage
-    printf "  %s\n" "REQUEST_DATA"
-    printf "    Request data (if the request_data parameter is specified, a POST request\n    will be made)\n"
     echo
 
     # :command.usage_examples
@@ -260,7 +293,7 @@ inspect_args() {
 
 # :command.user_lib
 # src/lib/functions/calculate_hash.sh
-# shellcheck shell=bash disable=SC2154
+# shellcheck disable=SC2154
 function calculate_hash() {
   local login password x_ndm_realm x_ndm_challenge
 
@@ -276,7 +309,6 @@ function calculate_hash() {
 }
 
 # src/lib/functions/convert_to.sh
-# shellcheck shell=bash
 convert_to() {
   input_format="${1:?input_format must be set}"
   output_format="${2:?output_format must be set}"
@@ -292,7 +324,6 @@ convert_json_to() {
 }
 
 # src/lib/functions/logging.sh
-# shellcheck shell=bash
 function error() {
   echo -e "($(date +'%Y-%m-%dT%H:%M:%S')) ERROR: $1" >&2
   exit 1
@@ -305,7 +336,6 @@ function log() {
 }
 
 # src/lib/http/get_http_base_url.sh
-# shellcheck shell=bash
 function get_http_base_url() {
   local scheme host port
   scheme="${1:?scheme must be set}"
@@ -316,7 +346,6 @@ function get_http_base_url() {
 }
 
 # src/lib/http/get_http_cookie_path.sh
-# shellcheck shell=bash
 function get_http_cookie_path() {
   local host port
 
@@ -327,7 +356,6 @@ function get_http_cookie_path() {
 }
 
 # src/lib/http/get_http_header_value.sh
-# shellcheck shell=bash
 function get_http_header_value() {
   local key response
 
@@ -341,7 +369,6 @@ function get_http_header_value() {
 }
 
 # src/lib/http/get_http_status_code.sh
-# shellcheck shell=bash
 function get_http_status_code() {
   local response
   response="${1:?response must be set}"
@@ -350,7 +377,6 @@ function get_http_status_code() {
 }
 
 # src/lib/http/http_request.sh
-# shellcheck shell=bash
 function http_request() {
   local host port scheme url_path request_data \
     output_path base_url cookie_path
@@ -388,7 +414,6 @@ function http_request_ohir() {
 }
 
 # src/lib/login.sh
-# shellcheck shell=bash
 function login() {
   local host port scheme verbose login password response
   host="${1:?host must be set}"
@@ -451,7 +476,6 @@ function login() {
 }
 
 # src/lib/request.sh
-# shellcheck shell=bash
 function request() {
   local host port scheme url_path request_data output \
     verbose login password response
@@ -489,8 +513,86 @@ function request() {
   log "Request successful, status_code: ${status_code}" "${verbose}"
 }
 
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# keencli completion                                       -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_keencli_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $'  '
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_keencli_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'completions\'*\'--scheme\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_keencli_completions_filter "http https")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'completions\'*\'--format\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_keencli_completions_filter "json yaml xml props")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'completions\'*\'-f\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_keencli_completions_filter "json yaml xml props")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'login\'*\'--scheme\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_keencli_completions_filter "http https")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'completions\'*\'-s\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_keencli_completions_filter "http https")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_keencli_completions_filter "--format --help --host --output --port --scheme --verbose -f -h -o -p -s")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'login\'*\'-s\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_keencli_completions_filter "http https")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'request\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_keencli_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'login\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_keencli_completions_filter "--help --host --port --scheme -h -p -s")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_keencli_completions_filter "--help --version -h -v completions login request")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'complete -F _keencli_completions keencli'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 # src/lib/validations/validate_file_path.sh
-# shellcheck shell=bash
 validate_file_path() {
   [[ -d "$1" ]] && echo "File cannot be a directory"
   [[ -d "$(dirname "$1")" ]] ||
@@ -498,7 +600,7 @@ validate_file_path() {
 }
 
 # src/lib/validations/validate_json.sh
-# shellcheck shell=bash disable=SC2154
+# shellcheck disable=SC2154
 validate_json() {
   if ! result=$(echo "$1" | yq -p json 2>&1); then
     echo "${result}"
@@ -509,7 +611,7 @@ validate_json() {
 # :command.function
 keencli_login_command() {
   # src/login_command.sh
-  # shellcheck shell=bash disable=SC2154 disable=SC2168
+  # shellcheck disable=SC2154 disable=SC2168
   local host port scheme login password
   host="${args[--host]}"
   port="${args[--port]}"
@@ -524,7 +626,7 @@ keencli_login_command() {
 # :command.function
 keencli_request_command() {
   # src/request_command.sh
-  # shellcheck shell=bash disable=SC2154 disable=SC2168
+  # shellcheck disable=SC2154 disable=SC2168
   local host port scheme verbose url_path request_data login password
   host="${args[--host]}"
   port="${args[--port]}"
@@ -551,6 +653,13 @@ keencli_request_command() {
   fi
 
   rm "${data_path}"
+
+}
+
+# :command.function
+keencli_completions_command() {
+  # src/completions_command.sh
+  send_completions
 
 }
 
@@ -629,6 +738,13 @@ parse_requirements() {
       action="request"
       shift
       keencli_request_parse_requirements "$@"
+      shift $#
+      ;;
+
+    completions)
+      action="completions"
+      shift
+      keencli_completions_parse_requirements "$@"
       shift $#
       ;;
 
@@ -771,7 +887,7 @@ keencli_request_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
-      --help)
+      --help | -h)
         long_usage=yes
         keencli_request_usage
         exit
@@ -786,6 +902,71 @@ keencli_request_parse_requirements() {
 
   # :command.command_filter
   action="request"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['url_path']+x} ]]; then
+
+          args['url_path']=$1
+          shift
+        elif [[ -z ${args['request_data']+x} ]]; then
+          # :argument.validations
+          if [[ -n $(validate_json "$1") ]]; then
+            printf "validation error in %s:\n%s\n" "REQUEST_DATA" "$(validate_json "$1")" >&2
+            exit 1
+          fi
+
+          args['request_data']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['url_path']+x} ]]; then
+    printf "missing required argument: URL_PATH\nusage: keencli request URL_PATH [REQUEST_DATA]\n" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+keencli_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help)
+        long_usage=yes
+        keencli_completions_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="completions"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -887,34 +1068,13 @@ keencli_request_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        if [[ -z ${args['url_path']+x} ]]; then
-
-          args['url_path']=$1
-          shift
-        elif [[ -z ${args['request_data']+x} ]]; then
-          # :argument.validations
-          if [[ -n $(validate_json "$1") ]]; then
-            printf "validation error in %s:\n%s\n" "REQUEST_DATA" "$(validate_json "$1")" >&2
-            exit 1
-          fi
-
-          args['request_data']=$1
-          shift
-        else
-          printf "invalid argument: %s\n" "$key" >&2
-          exit 1
-        fi
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
 
         ;;
 
     esac
   done
-
-  # :command.required_args_filter
-  if [[ -z ${args['url_path']+x} ]]; then
-    printf "missing required argument: URL_PATH\nusage: keencli request URL_PATH [REQUEST_DATA] [OPTIONS]\n" >&2
-    exit 1
-  fi
 
   # :command.default_assignments
   [[ -n ${args['--host']:-} ]] || args['--host']="192.168.1.1"
@@ -934,7 +1094,7 @@ keencli_request_parse_requirements() {
 
 # :command.initialize
 initialize() {
-  version="0.0.1"
+  version="0.0.2"
   long_usage=''
   set -e
 
@@ -952,6 +1112,7 @@ run() {
   case "$action" in
     "login") keencli_login_command ;;
     "request") keencli_request_command ;;
+    "completions") keencli_completions_command ;;
   esac
 }
 
