Bump keencli to bashly 1.1.10

diff --git a/keencli b/keencli
--- a/keencli
+++ b/keencli
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.2 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -567,12 +567,16 @@ keencli_self_test_usage() {
 }
 
 # :command.normalize_input
+# :command.normalize_input_function
 normalize_input() {
-  local arg flags
+  local arg flags passthru
+  passthru=false
 
   while [[ $# -gt 0 ]]; do
     arg="$1"
-    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+    if [[ $passthru == true ]]; then
+      input+=("$arg")
+    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
       input+=("${BASH_REMATCH[1]}")
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -583,6 +587,9 @@ normalize_input() {
       for ((i = 0; i < ${#flags}; i++)); do
         input+=("-${flags:i:1}")
       done
+    elif [[ "$arg" == "--" ]]; then
+      passthru=true
+      input+=("$arg")
     else
       input+=("$arg")
     fi
@@ -590,12 +597,15 @@ normalize_input() {
     shift
   done
 }
+
 # :command.inspect_args
 inspect_args() {
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
-    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
   else
     echo args: none
   fi
@@ -613,9 +623,19 @@ inspect_args() {
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
     echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
   fi
 
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
+    done
+  fi
 }
 
 # :command.user_lib
@@ -1073,6 +1093,9 @@ parse_requirements() {
 
   # :command.environment_variables_filter
 
+  env_var_names+=("KEENETIC_BASE_URL")
+  env_var_names+=("KEENETIC_USERNAME")
+  env_var_names+=("KEENETIC_PASSWORD")
   if [[ -z "${KEENETIC_USERNAME:-}" ]]; then
     printf "missing required environment variable: KEENETIC_USERNAME\n" >&2
     exit 1
@@ -1213,12 +1236,6 @@ keencli_request_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_base_url "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "$2")" >&2
-            exit 1
-          fi
-
           args['--baseurl']="$2"
           shift
           shift
@@ -1233,12 +1250,6 @@ keencli_request_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_file_path "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "$2")" >&2
-            exit 1
-          fi
-
           args['--output']="$2"
           shift
           shift
@@ -1253,7 +1264,6 @@ keencli_request_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-
           args['--format']="$2"
           shift
           shift
@@ -1271,17 +1281,12 @@ keencli_request_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['url_path']+x} ]]; then
-
           args['url_path']=$1
           shift
+        # :argument.case
         elif [[ -z ${args['request_data']+x} ]]; then
-          # :argument.validations
-          if [[ -n $(validate_json "$1") ]]; then
-            printf "validation error in %s:\n%s\n" "REQUEST_DATA" "$(validate_json "$1")" >&2
-            exit 1
-          fi
-
           args['request_data']=$1
           shift
         else
@@ -1302,6 +1307,25 @@ keencli_request_parse_requirements() {
 
   # :command.default_assignments
   [[ -n ${args['--baseurl']:-} ]] || args['--baseurl']="http://192.168.1.1"
+
+  # :command.validations
+  # :argument.validations
+  if [[ -v args['request_data'] && -n $(validate_json "${args['request_data']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "REQUEST_DATA" "$(validate_json "${args['request_data']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
+    exit 1
+  fi
 
   # :command.whitelist_filter
   if [[ ${args['--format']:-} ]] && [[ ! ${args['--format']:-} =~ ^(json|yaml|xml|props)$ ]]; then
@@ -1429,12 +1453,6 @@ keencli_show_system_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_base_url "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "$2")" >&2
-            exit 1
-          fi
-
           args['--baseurl']="$2"
           shift
           shift
@@ -1449,12 +1467,6 @@ keencli_show_system_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_file_path "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "$2")" >&2
-            exit 1
-          fi
-
           args['--output']="$2"
           shift
           shift
@@ -1469,7 +1481,6 @@ keencli_show_system_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-
           args['--format']="$2"
           shift
           shift
@@ -1487,8 +1498,8 @@ keencli_show_system_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['subcommand']+x} ]]; then
-
           args['subcommand']=$1
           shift
         else
@@ -1504,6 +1515,19 @@ keencli_show_system_parse_requirements() {
   # :command.default_assignments
   [[ -n ${args['--baseurl']:-} ]] || args['--baseurl']="http://192.168.1.1"
   [[ -n ${args['--format']:-} ]] || args['--format']="yaml"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
+    exit 1
+  fi
 
   # :command.whitelist_filter
   if [[ -n ${args['subcommand']:-} ]] && [[ ! ${args['subcommand']:-} =~ ^(caption|country|cpustat|debug|mode|zram)$ ]]; then
@@ -1547,12 +1571,6 @@ keencli_show_interface_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_base_url "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "$2")" >&2
-            exit 1
-          fi
-
           args['--baseurl']="$2"
           shift
           shift
@@ -1567,12 +1585,6 @@ keencli_show_interface_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_file_path "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "$2")" >&2
-            exit 1
-          fi
-
           args['--output']="$2"
           shift
           shift
@@ -1587,7 +1599,6 @@ keencli_show_interface_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-
           args['--format']="$2"
           shift
           shift
@@ -1605,12 +1616,12 @@ keencli_show_interface_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['interface_name']+x} ]]; then
-
           args['interface_name']=$1
           shift
+        # :argument.case
         elif [[ -z ${args['subcommand']+x} ]]; then
-
           args['subcommand']=$1
           shift
         else
@@ -1626,6 +1637,19 @@ keencli_show_interface_parse_requirements() {
   # :command.default_assignments
   [[ -n ${args['--baseurl']:-} ]] || args['--baseurl']="http://192.168.1.1"
   [[ -n ${args['--format']:-} ]] || args['--format']="yaml"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
+    exit 1
+  fi
 
   # :command.whitelist_filter
   if [[ -n ${args['subcommand']:-} ]] && [[ ! ${args['subcommand']:-} =~ ^(stat)$ ]]; then
@@ -1736,12 +1760,6 @@ keencli_show_ip_hotspot_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_base_url "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "$2")" >&2
-            exit 1
-          fi
-
           args['--baseurl']="$2"
           shift
           shift
@@ -1756,12 +1774,6 @@ keencli_show_ip_hotspot_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_file_path "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "$2")" >&2
-            exit 1
-          fi
-
           args['--output']="$2"
           shift
           shift
@@ -1776,7 +1788,6 @@ keencli_show_ip_hotspot_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-
           args['--format']="$2"
           shift
           shift
@@ -1794,8 +1805,8 @@ keencli_show_ip_hotspot_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['mac_address']+x} ]]; then
-
           args['mac_address']=$1
           shift
         else
@@ -1811,6 +1822,19 @@ keencli_show_ip_hotspot_parse_requirements() {
   # :command.default_assignments
   [[ -n ${args['--baseurl']:-} ]] || args['--baseurl']="http://192.168.1.1"
   [[ -n ${args['--format']:-} ]] || args['--format']="yaml"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
+    exit 1
+  fi
 
   # :command.whitelist_filter
   if [[ ${args['--format']:-} ]] && [[ ! ${args['--format']:-} =~ ^(json|yaml|xml|props)$ ]]; then
@@ -1850,12 +1874,6 @@ keencli_show_internet_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_base_url "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "$2")" >&2
-            exit 1
-          fi
-
           args['--baseurl']="$2"
           shift
           shift
@@ -1870,12 +1888,6 @@ keencli_show_internet_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_file_path "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "$2")" >&2
-            exit 1
-          fi
-
           args['--output']="$2"
           shift
           shift
@@ -1890,7 +1902,6 @@ keencli_show_internet_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-
           args['--format']="$2"
           shift
           shift
@@ -1919,6 +1930,19 @@ keencli_show_internet_parse_requirements() {
   # :command.default_assignments
   [[ -n ${args['--baseurl']:-} ]] || args['--baseurl']="http://192.168.1.1"
   [[ -n ${args['--format']:-} ]] || args['--format']="yaml"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
+    exit 1
+  fi
 
   # :command.whitelist_filter
   if [[ ${args['--format']:-} ]] && [[ ! ${args['--format']:-} =~ ^(json|yaml|xml|props)$ ]]; then
@@ -1958,12 +1982,6 @@ keencli_config_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_base_url "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "$2")" >&2
-            exit 1
-          fi
-
           args['--baseurl']="$2"
           shift
           shift
@@ -1978,12 +1996,6 @@ keencli_config_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_file_path "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "$2")" >&2
-            exit 1
-          fi
-
           args['--output']="$2"
           shift
           shift
@@ -2001,8 +2013,8 @@ keencli_config_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['configuration_file']+x} ]]; then
-
           args['configuration_file']=$1
           shift
         else
@@ -2023,6 +2035,19 @@ keencli_config_parse_requirements() {
 
   # :command.default_assignments
   [[ -n ${args['--baseurl']:-} ]] || args['--baseurl']="http://192.168.1.1"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
+    exit 1
+  fi
 
   # :command.whitelist_filter
   if [[ -n ${args['configuration_file']:-} ]] && [[ ! ${args['configuration_file']:-} =~ ^(startup-config|default-config|running-config)$ ]]; then
@@ -2062,12 +2087,6 @@ keencli_log_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_base_url "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "$2")" >&2
-            exit 1
-          fi
-
           args['--baseurl']="$2"
           shift
           shift
@@ -2082,12 +2101,6 @@ keencli_log_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_file_path "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "$2")" >&2
-            exit 1
-          fi
-
           args['--output']="$2"
           shift
           shift
@@ -2115,6 +2128,19 @@ keencli_log_parse_requirements() {
 
   # :command.default_assignments
   [[ -n ${args['--baseurl']:-} ]] || args['--baseurl']="http://192.168.1.1"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
+    exit 1
+  fi
 
 }
 
@@ -2148,12 +2174,6 @@ keencli_self_test_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_base_url "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "$2")" >&2
-            exit 1
-          fi
-
           args['--baseurl']="$2"
           shift
           shift
@@ -2168,12 +2188,6 @@ keencli_self_test_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_file_path "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "$2")" >&2
-            exit 1
-          fi
-
           args['--output']="$2"
           shift
           shift
@@ -2202,6 +2216,19 @@ keencli_self_test_parse_requirements() {
   # :command.default_assignments
   [[ -n ${args['--baseurl']:-} ]] || args['--baseurl']="http://192.168.1.1"
 
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--baseurl'] && -n $(validate_base_url "${args['--baseurl']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--baseurl BASEURL" "$(validate_base_url "${args['--baseurl']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--output'] && -n $(validate_file_path "${args['--output']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--output, -o OUTPUT" "$(validate_file_path "${args['--output']:-}")" >&2
+    exit 1
+  fi
+
 }
 
 # :command.initialize
@@ -2217,6 +2244,7 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
+  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
